---
title: "NBR values Combine csv"
output: html_document
---


# Overview


# Packages

```{r}
library(tidyverse)
```



# Data
## Orginal Data
```{r}
dforg = read.csv('../data/csv/data-uniqueID.csv')
```


## NBR data
```{r}
df1984 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1984.csv')
df1985 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1985.csv')
df1986 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1986.csv')
df1987 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1987.csv')
df1988 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1988.csv')
df1989 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1989.csv')
df1990 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1990.csv')
```

```{r}
df1991 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1991.csv')
df1992 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1992.csv')
df1993 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1993.csv')
df1994 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1994.csv')
df1995 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1995.csv')
df1996 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1996.csv')
df1997 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1997.csv')
df1998 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1998.csv')
df1999 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues1999.csv')
```

```{r}
df2000 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2000.csv')
df2001 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2001.csv')
df2002 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2002.csv')
df2003 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2003.csv')
df2004 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2004.csv')
df2005 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2005.csv')
df2006 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2006.csv')
df2007 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2007.csv')
df2008 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2008.csv')
df2009 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2009.csv')

```

```{r}
df2010 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2010.csv')
df2011 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2011.csv')
df2012 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2012.csv')
df2013 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2013.csv')
df2014 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2014.csv')
df2015 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2015.csv')
df2016 = read.csv('../data/NBR-US-States/2022-02-09_USHarvestNBRValues2016.csv')
```

# Original Data
```{r}
dforg1 = dforg %>% 
  dplyr::select(id, startLC1:endLC2) %>%
  unite("change1", startLC1, endLC1, remove = FALSE) %>%
  unite("change2", startLC2, endLC2, remove = FALSE) %>%
  unite("change3", change1, endLC2, remove = FALSE) 

dforg1
```

# NBR data combine
```{r}
df1984
```

```{r}
data84 = df1984 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1984)
data85 = df1985 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1985)
data86 = df1986 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1986)
data87 = df1987 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1987)
data88 = df1988 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1988)
data89 = df1989 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1989)
```

```{r}
data90 = df1990 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1990)
data91 = df1991 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1991)
data92 = df1992 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1992)
data93 = df1993 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1993)
data94 = df1994 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1994)
data95 = df1995 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1995)
data96 = df1996 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1996)
data97 = df1997 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1997)
data98 = df1998 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1998)
data99 = df1999 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr1999)
```

```{r}
data00 = df2000 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2000)
data01 = df2001 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2001)
data02 = df2002 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2002)
data03 = df2003 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2003)
data04 = df2004 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2004)
data05 = df2005 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2005)
data06 = df2006 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2006)
data07 = df2007 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2007)
data08 = df2008 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2008)
data09 = df2009 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2009)

```

```{r}
data10 = df2010 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2010)
data11 = df2011 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2011)
data12 = df2012 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2012)
data13 = df2013 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2013)
data14 = df2014 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2014)
data15 = df2015 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2015)
data16 = df2016 %>% dplyr::select( id, plotid, NAME:changeNote, startYear, endYear, nbr2016)
```

```{r}
head(data84)
head(data85)
head(data86)
```

```{r}
df_list <- list(data84, data85, data86, data87, data88, data89, data90, data91, data92, data93, data94, data95, data96, data97, data98, data99, data00, data01, data02, data03, data04, data05, data06, data07, data08, data09, data10, data11, data12, data13, data14, data15, data16)
```

```{r}
#merge all data frames in list
all_df = df_list %>% reduce(full_join, by=c("id", "plotid", "NAME", "STATE", "change", "changeNote", "startYear", "endYear"))
```


```{r}
all_df
```
```{r}
n_distinct(all_df$id)
```

# Join Original with NBR
```{r}
all_df1 = full_join(all_df, dforg1, by=c("id"))
all_df1
```

# Reorganize
```{r}

df2 = all_df1 %>%  rename("1984" = "nbr1984", 
                   "1985" = "nbr1985", 
                   "1986" = "nbr1986", 
                   "1987" = "nbr1987", 
                   "1988" = "nbr1988", 
                   "1989" = "nbr1989", 
                   "1990" = "nbr1990", 
                   "1991" = "nbr1991", 
                   "1992" = "nbr1992", 
                   "1993" = "nbr1993", 
                   "1994" = "nbr1994", 
                   "1995" = "nbr1995", 
                   "1996" = "nbr1996", 
                   "1997" = "nbr1997", 
                   "1998" = "nbr1998", 
                   "1999" = "nbr1999",
                   "2000" = "nbr2000",
                   "2001" = "nbr2001",
                   "2002" = "nbr2002",
                   "2003" = "nbr2003",
                   "2004" = "nbr2004",
                   "2005" = "nbr2005",
                   "2006" = "nbr2006",
                   "2007" = "nbr2007",
                   "2008" = "nbr2008",
                   "2009" = "nbr2009",
                   "2010" = "nbr2010",
                   "2011" = "nbr2011",
                   "2012" = "nbr2012",
                   "2013" = "nbr2013",
                   "2014" = "nbr2014",
                   "2015" = "nbr2015",
                   "2016" = "nbr2016")  


df2
```
```{r eval=FALSE, include=FALSE}
write.csv(df2, '../outputs/csv/dataAllNBRYears.csv',  row.names = FALSE)
```

```{r}

df3 = df2 %>%
  pivot_longer(!c("id", "plotid", "NAME", "STATE", "change", "changeNote", "startYear", "endYear", "change1", "startLC1", "endLC1", "change2", "startLC2", "endLC2", "change3"), names_to = "nbrYr", values_to = "nbr") %>%
  pivot_longer(!c("id", "plotid", "NAME", "STATE", "change", "changeNote", "nbrYr", "nbr",  "change1", "startLC1", "endLC1", "change2", "startLC2", "endLC2", "change3"), names_to = "startEnd", values_to = "year") %>%
  mutate(prePost = ifelse(startEnd == "startYear", "preNbr", "postNbr")) 

df3
```
```{r eval=FALSE, include=FALSE}
write.csv(df3, '../outputs/csv/dataAllNBRYearsLongFormData.csv',  row.names = FALSE)
```
```{r}
df4 <- df3[df3$nbrYr==df3$year, ]

df4
```
```{r}
str(df4$prePost)
```

letter = ifelse(grade %in% 60:69, "D",
 mutate(prePost = factor(prePost, c( 'PreNbr', 'postNbr'), ordered = T)) 
```{r eval=FALSE, include=FALSE}
df5 <- df4 %>% 
  mutate(prePost = factor(ifelse(startEnd == "startYear", "preNBR", "postNBR"), ordered = T)) 

df5
```  
```{r}
df5 = df4 %>%
  group_by(id) %>% 
  mutate(diff = lag(nbr, 1) - nbr) 
df5
```

%>%
  dplyr::select(id, plotid, diff) %>%
  drop_na()


```{r}
df6 = df5 %>% dplyr::select(id, plotid, NAME, change, changeNote, change1, change2, change3, startLC1, endLC1, startLC2, endLC2, diff) %>%
  rename(dnbr = diff) %>%
  drop_na() %>%
  filter(change=="Harvest")

df6
  
```
```{r}
df7 = df6 %>% filter(change1 %in% c("Trees_Trees", "Trees_Shrubs", "Trees_Grass/forb/herb", "Trees_Barren"))
df7
```
```{r}
unique(df6$endLC2)

df6 %>% filter(endLC2=="trees")
```
```{r}
target_endLC1 = c("Trees", "Grass/forb/herb", "Barren", "Shrubs")
target_endLC2 = c("trees", "grassForbHerb", "grassForbHerb|naturalBarren", "shrubs", "naturalBarren" )
df8 = df6 %>% 
  filter(startLC1 =="Trees") %>%
  filter(endLC1 %in% target_endLC1) %>%
  filter(endLC2 %in% target_endLC2)

df8
```
```{r}
target_notes = c("thinning", "clearcut")
df9 = df6 %>% filter(changeNote %in% target_notes)

df9
```

```{r}

df10 = df5 %>% filter(changeNote == "clearcut")

df10
```

# Plots
```{r}
plot1 = ggplot(data = df7, aes(x=dnbr, y=change1)) +
  geom_boxplot()

plot1
```
```{r eval=FALSE, include=FALSE}
ggsave("../figures/boxplot1.png", plot = plot1, width = 6, height = 4, units = c("in"), dpi = 600)
```

```{r}
p11 = ggplot(data = df7, aes(x=dnbr, y=change3)) +
  geom_boxplot()

p11
```



```{r}
p2 <- df7 %>%
  ggplot( aes(x=dnbr, fill=change1)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080", "#b3697a", "#7ab369")) +
    theme_bw() +
    labs(fill="")

p2
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/HistogramOverlap.png", plot = p2, width = 6, height = 6, units = c("in"), dpi = 600)
```

```{r}
p3 <- df7 %>%
  ggplot( aes(x=dnbr, fill=change1)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity', binwidth = 50) +
    scale_fill_manual(values=c("#69b3a2", "#404080", "#b3697a", "#7ab369")) +
    theme_bw() +
    labs(fill="") +
  facet_wrap(~change1)

p3
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/HistogramFacetLC1.png", plot = p3, width = 6, height = 6, units = c("in"), dpi = 600)
```


```{r}
p4 <- df8 %>%
  ggplot( aes(x=dnbr, fill=change3)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity', binwidth = 50) +
    scale_fill_manual(values=c("#69b3a2", "#404080", "#b3697a", "#7ab369", "#69b3a2", "#404080", "#b3697a", "#7ab369", "#69b3a2", "#404080", "#b3697a", "#7ab369", "#69b3a2")) +
    theme_bw() +
    labs(fill="") +
  facet_wrap(~change3) + 
  theme(legend.position="none")
  

p4
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/HistgramFacetLC1LC2.png", plot = p4, width =11, height = 8, units = c("in"), dpi = 600)
```



```{r}
plot2 = ggplot(data = df8, aes(x=dnbr, y=change3)) +
  geom_boxplot()

plot2
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/boxplotLC1LC2.png", plot = plot2, width = 8, height = 7, units = c("in"), dpi = 600)
```

```{r}
p5 <- df9 %>%
  ggplot( aes(x=dnbr, fill=changeNote)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    theme_bw() +
    labs(fill="")

p5
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/HistogramOverlapChangeNotes.png", plot = p5, width = 6, height = 4, units = c("in"), dpi = 600)
```


# Manual approach
```{r}

dnbr1 = all_df %>%
  filter(startYear==1984) %>%
  filter(endYear==1985) %>%
  mutate(dnbr = nbr1984-nbr1985) %>%
  dplyr::select(plotid:endYear, nbr1984, nbr1985, dnbr)
dnbr1
```

```{r}

dnbr2 = all_df %>%
  filter(startYear==1985) %>%
  filter(endYear==1986) %>%
  mutate(dnbr = nbr1985-nbr1986) %>%
  dplyr::select(plotid:endYear, nbr1985, nbr1986, dnbr)

dnbr2
```

```{r}

dnbr3 = all_df %>%
  filter(startYear==1986) %>%
  filter(endYear==1987) %>%
  mutate(dnbr = nbr1986-nbr1987) %>%
  dplyr::select(plotid:endYear, nbr1986, nbr1987, dnbr)

dnbr3
```

```{r}

dnbr4 = all_df %>%
  filter(startYear==1987) %>%
  filter(endYear==1988) %>%
  mutate(dnbr = nbr1987-nbr1988) %>%
  dplyr::select(plotid:endYear, nbr1987, nbr1988, dnbr)

dnbr4
```


```{r}

dnbr5 = all_df %>%
  filter(startYear==1988) %>%
  filter(endYear==1989) %>%
  mutate(dnbr = nbr1988-nbr1989) %>%
  dplyr::select(plotid:endYear, nbr1988, nbr1989, dnbr)

dnbr5
```
```{r}

dnbr6 = all_df %>%
  filter(startYear==1989) %>%
  filter(endYear==1990) %>%
  mutate(dnbr = nbr1989-nbr1990) %>%
  dplyr::select(plotid:endYear, nbr1989, nbr1990, dnbr)

dnbr6
```

```{r}

dnbr7 = all_df %>%
  filter(startYear==1990) %>%
  filter(endYear==1991) %>%
  mutate(dnbr = nbr1990-nbr1991) %>%
  dplyr::select(plotid:endYear, nbr1990, nbr1991, dnbr)

dnbr7
```

```{r}

dnbr8 = all_df %>%
  filter(startYear==1991) %>%
  filter(endYear==1992) %>%
  mutate(dnbr = nbr1991-nbr1992) %>%
  dplyr::select(plotid:endYear, nbr1991, nbr1992, dnbr)

dnbr8
```

```{r}

dnbr9 = all_df %>%
  filter(startYear==1992) %>%
  filter(endYear==1993) %>%
  mutate(dnbr = nbr1992-nbr1993) %>%
  dplyr::select(plotid:endYear, nbr1992, nbr1993, dnbr)

dnbr9
```

```{r}

dnbr10 = all_df %>%
  filter(startYear==1993) %>%
  filter(endYear==1994) %>%
  mutate(dnbr = nbr1993-nbr1994) %>%
  dplyr::select(plotid:endYear, nbr1993, nbr1994, dnbr)

dnbr10
```

```{r}

dnbr11 = all_df %>%
  filter(startYear==1994) %>%
  filter(endYear==1995) %>%
  mutate(dnbr = nbr1994-nbr1995) %>%
  dplyr::select(plotid:endYear, nbr1994, nbr1995, dnbr)

dnbr11
```

```{r}

dnbr12 = all_df %>%
  filter(startYear==1995) %>%
  filter(endYear==1996) %>%
  mutate(dnbr = nbr1995-nbr1996) %>%
  dplyr::select(plotid:endYear, nbr1995, nbr1996, dnbr)

dnbr12
```

```{r}

dnbr13 = all_df %>%
  filter(startYear==1996) %>%
  filter(endYear==1997) %>%
  mutate(dnbr = nbr1996-nbr1997) %>%
  dplyr::select(plotid:endYear, nbr1996, nbr1997, dnbr)

dnbr13
```

```{r}

dnbr14 = all_df %>%
  filter(startYear==1997) %>%
  filter(endYear==1998) %>%
  mutate(dnbr = nbr1997-nbr1998) %>%
  dplyr::select(plotid:endYear, nbr1997, nbr1998, dnbr)

dnbr14
```

```{r}

dnbr15 = all_df %>%
  filter(startYear==1997) %>%
  filter(endYear==1998) %>%
  mutate(dnbr = nbr1997-nbr1998) %>%
  dplyr::select(plotid:endYear, nbr1997, nbr1998, dnbr)

dnbr15
```